WORDATA/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('analysis_text.urls')),
    path('', include('login.urls')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

analysis_text/urls.py
from django.urls import path
from . import views

app_name = 'analysis_text'
urlpatterns = [
    path('userinputform/', views.userinputform, name='userinputform'),
    path('form_list/', views.form_list, name='form_list'),
    path('dataframe/<int:form_id>/', views.dataframe, name='dataframe'),
    path('suneung_words/', views.suneung_words, name='suneung_words'),
    path('pyeonggawon_words/', views.pyeonggawon_words, name='pyeonggawon_words'),
    path('dataframe_words/', views.dataframe_words, name='dataframe_words'),
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
]

analysis_text/models.py
from django.db import models
import os

#사용자가 올리는 파일이 저장되고 분석에 관한 세부사항이 저장되는 테이블
class Userinput(models.Model):
    file = models.FileField(upload_to='documents/')
    frequency = models.IntegerField(default=10)
    word_except = models.IntegerField(default=False)
    times = models.IntegerField(default=20)

    def __str__(self):
        return os.path.basename(self.file.path)

#사용자가 분석을 요청한 단어가 저장되는 테이블
class Dataframe(models.Model):
    numbering = models.IntegerField(default=0, blank=True, null=True)
    word = models.CharField(max_length=50, blank=True, null=True)
    part_of_speech = models.CharField(max_length=20, blank=True, null=True)
    meaning = models.CharField(max_length=40, blank=True, null=True)
    example_sentence = models.TextField(blank=True, null=True)
    sentence_interpretation = models.TextField(blank=True, null=True)
    word_of_frequency = models.IntegerField(default=0, blank=True, null=True)

    def __str__(self):
        return str(self.word)

#수능 단어가 저장되는 테이블
class Suneung(models.Model):
    numbering = models.IntegerField(default=0, blank=True, null=True)
    word = models.CharField(max_length=50, blank=True, null=True)
    part_of_speech = models.CharField(max_length=20, blank=True, null=True)
    meaning = models.CharField(max_length=40, blank=True, null=True)
    example_sentence = models.TextField(blank=True, null=True)
    sentence_interpretation = models.TextField(blank=True, null=True)
    word_of_frequency = models.IntegerField(default=0, blank=True, null=True)

    def __str__(self):
        return str(self.word)

#평가원 단어가 저장되는 테이블
class Pyeonggawon(models.Model):
    numbering = models.IntegerField(default=0, blank=True, null=True)
    word = models.CharField(max_length=50, blank=True, null=True)
    part_of_speech = models.CharField(max_length=20, blank=True, null=True)
    meaning = models.CharField(max_length=40, blank=True, null=True)
    example_sentence = models.TextField(blank=True, null=True)
    sentence_interpretation = models.TextField(blank=True, null=True)
    word_of_frequency = models.IntegerField(default=0, blank=True, null=True)

    def __str__(self):
        return str(self.word)

analysis_text/forms.py
from django import forms
from .models import Userinput

#사용자가 파일을 올리고 분석할 단어의 범위와 단어의 개수를 정하는 form
class UserinputForm(forms.ModelForm):
    class Meta:
        model = Userinput
        fields = ['file', 'frequency', 'word_except', 'times']
        #'file': 파일을 받을 field
        #'frequency': 분석할 파일의 단어 빈도수를 정하는 field. frequency이하의 단어는 단어장 형성에 포함되지 않는다.
        #'word_except': 전처리할 단어를 정하는 field
        #'times': 단어장에 들어갈 단어 개수를 정하는 field

analysis_text/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import *
from .forms import UserinputForm

# import modules
# read data
import docx
from PyPDF2 import PdfFileReader

# Analysis
from nltk import *
import nltk
nltk.download('stopwords')
nltk.download('averaged_perceptron_tagger')
nltk.download('wordnet')
from nltk.corpus import stopwords
from nltk.tokenize import WordPunctTokenizer
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib
import zipfile
import re
import sys
import os

# Crawling
import requests
from bs4 import BeautifulSoup

# UnZip
def getZip(zipFile):
    unzip = zipfile.ZipFile(zipFile)
    unzip.extractall('zipfolder')
    unzip.close()
    path = os.getcwd()
    path += '\zipfolder'
    print("*Zip 해제 완료")
    return path
    
#하위 dir에 있는 파일들을 list로 반환한다.
def getFiles(path):
    files = []
    for a, b, c in os.walk(path):
        for f in c:
            file = os.path.join(a, f)
            files.append(file)
    print("*파일 스캔 완료")
    return files

#function of readding data
def getTextPDF(pdfFileName):
    with open(pdfFileName, 'rb') as f:
        read_pdf = PdfFileReader(f)  
        text = []
        for i in range(0, read_pdf.getNumPages()):
            text.append(read_pdf.getPage(i).extractText())
    return '\n'.join(text)

def getTextWord(wordFileName):
    doc = docx.Document(wordFileName)
    fullText = []
    for text in doc.paragraphs:
        fullText.append(text.text)
    return '\n'.join(fullText)

def read_file(file):
    text = []
    if file[-3:] == 'pdf':
        text.append(getTextPDF(file))
    elif file[-4:] == 'docx':
        text.append(getTextWord(file))
    return text

def removeFolder(file):
    if os.path.isfile(file):
        os.remove(file)
        
#텍스트 분석
def wordata(file, n, wordExcept = False, lenth = False):
    FileName = file.path
    mode = ''
    textHeap = []

    if FileName[-3:] == 'zip':
        print("*Zip 파일을 입력 받습니다. ")
        FileName = getZip(FileName)
        FileName = getFiles(FileName)
        mode = 'Zip'

    #mode에 따라 선택적 처리
    print("*파일 읽기를 시작합니다.")


    if mode == 'Zip':
        for file in FileName:
            textHeap += read_file(file)

    else:
        textHeap = read_file(FileName)

    #집 해제된 폴더안의 파일 삭제
    for file in FileName:
        removeFolder(file)
        
    #Tokenization
    print("*텍스트 분석을 시작합니다.")
    tokenizer = WordPunctTokenizer()
    TokenizedWords = []

    for text in textHeap:
        TokenizedWords += tokenizer.tokenize(text)
    print("*문서 안의 전체 단어 개수: {}" .format(len(TokenizedWords))) 
    if mode == 'Zip':
        for file in FileName:
            removeFolder(file)

    #불용어 load
    os.chdir(os.getcwd())
    system_path = os.getcwd()
    now_path = str(system_path) +'\\errorword'
    errorWords = pd.read_csv(now_path + "\\errorWords.csv", header = None)

    stop_words = set(stopwords.words('english')) # NLTK에서 기본적으로 정의하고 있는 불용어
    stop_words = stop_words | set(pd.Series(errorWords[0]).to_list())
    
    # 과정별 단어 제거
    if wordExcept == 1:
        elementWord = pd.read_csv(now_path + "\\초등800.csv", header = None)
        stop_words = stop_words | set(pd.Series(elementWord[0]).to_list())
        print('초등 영단어 제거 성공')
    elif wordExcept == 2:
        middleWord = pd.read_csv(now_path + "\\중등2000.csv", header = None)
        stop_words = stop_words | set(pd.Series(middleWord[0]).to_list())
        print('중등 영단어 제거 성공')
    elif wordExcept == 3:
        highWord = pd.read_csv(now_path + "\\고등3000.csv", header = None)
        stop_words = stop_words | set(pd.Series(highWord[0]).to_list())
        print('고등 영단어 제거 성공')

    np_words = np.array(TokenizedWords) # Tokenized words를 numpy array type으로 형 변환
    delete_index = [] # 불용어 index번호를 저장할 list

    print("*1차 불용어 제거를 시작합니다.")
    sepWords = []
    testSepWord = 0  #한 단어이지만 분리된 단어인지 여부를 확인. 0 or 1
    for i in range(len(np_words)):
        np_words[i] = re.sub("[^a-zA-Z]", "__", np_words[i])  #영어만 가져온다
        
        if testSepWord == 1:
            np_words[i] = beforeWord + np_words[i]
        if np_words[i][-2:] == '__':
            testSepword = 1
            beforeWord = np_words[i][:-2]
            delete_index.append(i)
        else:
            testSepWord = 0
        if np_words[i].count('__') > 0 and np_words[i][-2:] != '__':
            sepWords + np_words[i].split('__')
            delete_index.append(i)
        
        if (np_words[i] in stop_words) == True: 
            delete_index.append(i)
        if len(np_words[i]) <= 1:
            delete_index.append(i)

    TrimmedWords = np.delete(np_words, delete_index) #불용어 index를 삭제
    TrimmedWords = list(TrimmedWords) + sepWords
    print('제거 후 단어 수: {}' .format(len(TrimmedWords)))
    
    
     # 품사 태깅
    tagged_list = pos_tag(TrimmedWords)
    verb =[]
    noun = []
    adject = []
    adverb = []
    for w in tagged_list:
        if w[1]=='VB' or  w[1]=='VBD' or w[1] =='VBG' or w[1] == 'VBN' or w[1] == 'VBP' or w[1]=='JJ':
            verb.append(w) 
        elif w[1]=='NNS' or w[1] == 'NNPS' or w[1]== 'NN':
            if len(w[0]) > 3 and w[0][-3] == 'ing': #만약 현재분사로써 대문자인 -ing 형이 온다면 아래를 실행
                verb.append(w)
            else:
                noun.append(w)
        elif w[1] =='JJ' or w[1]=='JJR' or w[1] == 'JJS':
            adject.append(w)
        elif w[1]=='RBR' or w[1] == 'RBS' or w[1]=='RB':
            adverb.append(w)

    verb = untag(verb)
    noun = untag(noun)
    adject = untag(adject)
    adverb = untag(adverb)

    restoredVerb = [] # 동사 원형 복원
    for v in verb:
        restoredVerb.append(WordNetLemmatizer().lemmatize(v.lower(), pos='v'))                       
    restoredNoun = [WordNetLemmatizer().lemmatize(w, pos='n') for w in noun]  #명사 원형 복원
    restoredAdject = [WordNetLemmatizer().lemmatize(w, pos='a') for w in adject]  #형용사 원형 복원
    restoredAdverb = [WordNetLemmatizer().lemmatize(w, pos='r') for w in adverb]  #부사 원형 복원

    #복원된 데이터 통합
    combinedWords = restoredVerb + restoredNoun + restoredAdject + restoredAdverb
    print("*필터된 단어의 개수: {}" .format(len(combinedWords)))
    
    np_words = np.array(combinedWords) # Tokenized words를 numpy array type으로 형 변환
    delete_index_2 = [] # 불용어 index번호를 저장할 list

    print("*2차 불용어 제거를 시작합니다.")
    for i in range(len(np_words)):
    #     np_words[i] = np_words[i].lower()  #모든 단어를 소문자로 변경
        if (np_words[i] in stop_words) == True: 
            delete_index_2.append(i)
        if len(np_words[i]) >= 20 or len(np_words[i]) <= 2:
            delete_index_2.append(i)
    TrimmedWords = np.delete(np_words, delete_index_2) #불용어 index를 삭제
    print('제거 후 단어 수: {}' .format(len(TrimmedWords)))
    resultWords = TrimmedWords
    
    overNum = n  #빈도수 개수 이상 단어를 뽑아냄

    print('*중복된 단어의 갯수를 셉니다.')
    cleansing = pd.Series(resultWords).value_counts()
    removedOverlabWords = pd.DataFrame()
    removedOverlabWords['Word'] = cleansing.index
    removedOverlabWords['value count'] = cleansing.values
    removedOverlabWords = removedOverlabWords[removedOverlabWords['value count']> overNum ]
    print("*** 단어 분석 완료 ***")
    print('{}개 이상의 빈도수 단어를 추출합니다.'.format(overNum))
    print("최종 단어 수 : {}" .format(removedOverlabWords['Word'].count()))
    
    
  
    #그래프 생성
    img_path = str(system_path) +'\\static\\img'

    lenth_1 = 50
    start = 50
    if len(removedOverlabWords) < 50:
        lenth_1 = len(removedOverlabWords)
        start = 10
    cumsum = (np.cumsum(removedOverlabWords['value count'][:50]).to_list()[-1]) * 1.2
    count = removedOverlabWords['value count'].to_list()[0] *1.2

    fig, ax1 = plt.subplots()
    fig.set_size_inches(17, 10) #크기 바꾸기(inch 단위)

    color = '#B0E0E6'
    ax1.set_ylabel('', color='black', size=30)  # we already handled the x-label with ax1
    ax1.bar(range(1,lenth_1+1), np.cumsum(removedOverlabWords['value count'][:lenth_1]), color=color, width=0.5, label='Cumsum')

    ax2 = ax1.twinx()

    matplotlib.rc('ytick', labelsize=25) 
    matplotlib.rc('xtick', labelsize=30) 
    color = '#5c3090'
    ax2.set_ylabel(' ', color='black', size=30)
    ax2.plot(range(1,lenth_1+1), removedOverlabWords['value count'][:lenth_1], color=color, label='Freqency',linewidth = 15)


    lines, labels = ax1.get_legend_handles_labels()
    lines2, labels2 = ax2.get_legend_handles_labels()
    ax2.legend(lines + lines2, labels + labels2, prop={'size': 20})
    ax2.set_ylim(start, count)
    ax1.set_ylim(-20,cumsum)
    plt.grid()
    fig.tight_layout() 
    fig.savefig(img_path + '\\graph.png') #현재 figure 저장하기
    print('그래프 생성 완료')

   #lenth 파라미터를 받음
    if lenth == False:
        WordsLenth = removedOverlabWords['Word'].to_list()
    else:
        lenth -= 1
        WordsLenth = removedOverlabWords['Word'].loc[:lenth].to_list()

    word_url=[] #단어 검색 후 첫번째 url

    dictlink='https://endic.naver.com' #네이버사전 홈페이지 url

    for i in range(len(WordsLenth)): #테스트 단어 갯수만큼 반복
        url="https://endic.naver.com/search.nhn?sLn=kr&query="+ WordsLenth[i] #단어검색 뒤에 영단어를 붙혀 url 넘겨줌
        res=requests.get(url).text #url을 requests한걸 text로 가져와 res 에 저장
        soup=BeautifulSoup(res,"lxml") #res를 beautiful soup에 넘겨줌
        finded_href = soup.findAll("a",href=re.compile("^(/enkrEntry)"))
        if len(finded_href) != 0:
            for link in finded_href: #a 태그의 href를 가져올건데 (/enkrEntry) 이부분이 가져올 url들에 반복되어 그 href를 다찾음
                if 'href' in link.attrs: #만약 link의 모든속성에 href가 있따면
                    word=link.attrs['href'] #href의 모든속성을 word에 저장 즉 그 사전검색하면 나오는 두번째 url 저장
                    word=dictlink+word #네이버 사전 홈페이지+2번째 페이지 url을 넘겨준다.
                    word_url.append(word) #합친 url을 word_url의 리스트에 넣음
                    break #첫번째 word_url만 뽑아서 멈춤
        else:
            word_url.append(None)
            

    selecter = [
        ['span.fnt_k06',
         'p.bg span.fnt_e07._ttsText',
         'dd.first p span.fnt_k10',
         'span.fnt_syn',
         '#content > div.word_view > div.tit > h3'],

templates/analysis_text/dataframe.html
{% extends 'layout.html' %}

{% block content %}


<div class="contents" style="background: url(../../static/img/analysis_gogo_back03.jpg); background-size: cover; opacity: 0.9;">
    <div class="container">
        <div class="row">
            <div class="analysis">
               <div>
                    <div class="gogo">
                            <a href="{% url 'analysis_text:dataframe_words' %}"><button type="">결과 확인</button></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/analysis_text/dataframe_words.html
{% extends 'layout.html' %}

{% block content %}

<div class="contents" style=" background-color: #F6F6F6; margin-top: -55px;  padding: 3rem 0;">
    <div class="container">
        <div class="row" style="display: block; text-align: center;">
            <!-- <div class="uploadResult_info">
               <h2>&#10003; 단어 순위 보기 &#10003;</h2>
            </div> -->
            <!-- //uploadResult_info -->
            <div class="suneung" style="margin-top: 10rem; height: 100px;">
                <h2>&#9995;단어 빈도수를 분석한 결과를 알려드립니다.&#9995;</h2>
            </div>
            <div class="word_graph">
                <div class="graph_img">
                    <img src="../../static/img/graph.png" style="width: 50rem;";>
                </div>
            </div>
            <div class="endWord">
                <div class="word_user">
                {% for word in dataframe_words %}
                    {% if word.numbering != Null %}
                    <div class="UR_margin"></div>
                    <div class="UR_box">
                        <div class="UR_one">
                            <div class="UR_eng">
                                <span class="UR_eng_first">{{word.numbering}}&nbsp;</span><span>&nbsp;<span style="font-weight: bold;">{{word.word}}</span></span>
                            </div>
                            <div class="UR_fq">
                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Freq : {{word.word_of_frequency}}
                            </div>
                        </div>
                        <!-- //UR_one -->
                        
                        <div class="UR_two">
                            <div class="UR_mean">
                                <span class="UR_mean_first">{{word.part_of_speech}}</span><span class="UR_mean_second">&nbsp;{{word.meaning}}</span>
                            </div>
                            <div class="UR_ex">
                                {{word.example_sentence}}
                            </div>
                            <div class="UR_exkor">
                                {{word.sentence_interpretation}}
                            </div>
                        </div>
                        <!-- //UR_two -->
                        
                    </div>
                    <!-- //UR_box -->
                    {% else%}
                    <div class="UR_box">
                        <div class="UR_one">
                            <div class="UR_eng">
                                <span class="UR_eng_first">&nbsp;</span><span>&nbsp;</span>
                            </div>
                            <div class="UR_fq">
                                
                            </div>
                        </div>
                        <!-- //UR_one -->
                        
                        <div class="UR_two">
                            <div class="UR_mean">
                                <span class="UR_mean_first">{{word.part_of_speech}}</span><span class="UR_mean_second">&nbsp;{{word.meaning}}</span>
                            </div>
                            <div class="UR_ex">
                                {{word.example_sentence}}
                            </div>
                            <div class="UR_exkor">
                                {{word.sentence_interpretation}}
                            </div>
                        </div>
                        <!-- //UR_two -->
                        
                    </div>
                    <!-- //UR_box -->
                    {% endif %}
                {% endfor %}
                </div>
                <!-- //word_user -->
            </div>
        </div>
    </div>
</div>
<!-- <p><a href="{% url 'main:home' %}">다른 단어 리스트를 보고싶다면??</a><p> -->
{% endblock %}

templates/analysis_text/form_list.html
<!--nav바에서 폼리스트 부분-->
{% extends 'layout.html' %}

{% block content %} 
{% if form %}
 
<div class="contents" style="background: url(../../static/img/analysis_gogo_back04.jpg); background-size: cover; opacity: 0.9;">
    <div class="container">
        <div class="row">
            <div class="analysis">
               <div>
                    <div class="gogo">
                        <a href="{% url 'analysis_text:dataframe' form.id %}"><button type="">분석 바로가기</button></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endif %}
{% endblock %} 

templates/analysis_text/pyeonggawon_words.html
{% extends 'layout.html' %}

{% block content %}

<div class="contents" style=" background-color: #F6F6F6; margin-top: -55px;">
    <div class="container">
        <div class="row" style="display: block; text-align: center;">
            <div class="uploadResult_info">
               <h2>&#10003; 단어 순위 보기 &#10003;</h2>
            </div>
            <!-- //uploadResult_info -->
            
            <div class="word_graph">
                <div class="graph_img">
                    <img src="../../static/img/pyeong.png" style="width: 50rem;";>
                </div>
            </div>
            <div class="endWord">
                <div class="word_user">
                {% for word in pyeonggawon_words %}
                    {% if word.numbering != Null %}
                    <div class="UR_margin"></div>
                    <div class="UR_box">
                        <div class="UR_one">
                            <div class="UR_eng">
                                <span class="UR_eng_first">{{word.numbering}}&nbsp;</span><span>&nbsp;<span style="font-weight: bold;">{{word.word}}</span></span>
                            </div>
                            <div class="UR_fq">
                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Freq : {{word.word_of_frequency}}
                            </div>
                        </div>
                        <!-- //UR_one -->
                        
                        <div class="UR_two">
                            <div class="UR_mean">
                                <span class="UR_mean_first">{{word.part_of_speech}}</span><span class="UR_mean_second">&nbsp;{{word.meaning}}</span>
                            </div>
                            <div class="UR_ex">
                                {{word.example_sentence}}
                            </div>
                            <div class="UR_exkor">
                                {{word.sentence_interpretation}}
                            </div>
                        </div>
                        <!-- //UR_two -->
                        
                    </div>
                    <!-- //UR_box -->
                    {% else%}
                    <div class="UR_box">
                        <div class="UR_one">
                            <div class="UR_eng">
                                <span class="UR_eng_first">&nbsp;</span><span>&nbsp;</span>
                            </div>
                            <div class="UR_fq">
                                
                            </div>
                        </div>
                        <!-- //UR_one -->
                        
                        <div class="UR_two">
                            <div class="UR_mean">
                                <span class="UR_mean_first">{{word.part_of_speech}}</span><span class="UR_mean_second">&nbsp;{{word.meaning}}</span>
                            </div>
                            <div class="UR_ex">
                                {{word.example_sentence}}
                            </div>
                            <div class="UR_exkor">
                                {{word.sentence_interpretation}}
                            </div>
                        </div>
                        <!-- //UR_two -->
                        
                    </div>
                    <!-- //UR_box -->
                    {% endif %}
                {% endfor %}
                </div>
                <!-- //word_user -->
            </div>
        </div>
    </div>
</div>
<p><a href="{% url 'main:home' %}">다른 단어 리스트를 보고싶다면??</a><p>
{% endblock %}

templates/analysis_text/suneung_words.html
{% extends 'layout.html' %}

{% block content %}

<div class="contents" style=" background-color: #F6F6F6; margin-top: -55px;">
    <div class="container">
        <div class="row" style="display: block; text-align: center;">
            <div class="uploadResult_info">
               <h2>&#10003; 단어 순위 보기 &#10003;</h2>
            </div>
            <!-- //uploadResult_info -->
            
            <div class="word_graph">
                <div class="graph_img">
                    <img src="../../static/img/soo.png" style="width: 50rem;";>
                </div>
            </div>
            <div class="endWord">
                <div class="word_user">
                {% for word in suneung_words %}
                    {% if word.numbering != Null %}
                    <div class="UR_margin"></div>
                    <div class="UR_box">
                        <div class="UR_one">
                            <div class="UR_eng">
                                <span class="UR_eng_first">{{word.numbering}}&nbsp;</span><span>&nbsp;<span style="font-weight: bold;">{{word.word}}</span></span>
                            </div>
                            <div class="UR_fq">
                                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Freq : {{word.word_of_frequency}}
                            </div>
                        </div>
                        <!-- //UR_one -->
                        
                        <div class="UR_two">
                            <div class="UR_mean">
                                <span class="UR_mean_first">{{word.part_of_speech}}</span><span class="UR_mean_second">&nbsp;{{word.meaning}}</span>
                            </div>
                            <div class="UR_ex">
                                {{word.example_sentence}}
                            </div>
                            <div class="UR_exkor">
                                {{word.sentence_interpretation}}
                            </div>
                        </div>
                        <!-- //UR_two -->
                        
                    </div>
                    <!-- //UR_box -->
                    {% else%}
                    <div class="UR_box">
                        <div class="UR_one">
                            <div class="UR_eng">
                                <span class="UR_eng_first">&nbsp;</span><span>&nbsp;</span>
                            </div>
                            <div class="UR_fq">
                                
                            </div>
                        </div>
                        <!-- //UR_one -->
                        
                        <div class="UR_two">
                            <div class="UR_mean">
                                <span class="UR_mean_first">{{word.part_of_speech}}</span><span class="UR_mean_second">&nbsp;{{word.meaning}}</span>
                            </div>
                            <div class="UR_ex">
                                {{word.example_sentence}}
                            </div>
                            <div class="UR_exkor">
                                {{word.sentence_interpretation}}
                            </div>
                        </div>
                        <!-- //UR_two -->
                        
                    </div>
                    <!-- //UR_box -->
                    {% endif %}
                {% endfor %}
                </div>
                <!-- //word_user -->
            </div>
        </div>
    </div>
</div>
<p><a href="{% url 'main:home' %}">다른 단어 리스트를 보고싶다면??</a><p>
{% endblock %}

templates/analysis_text/userinputform.html
<!--유저가 폼 입력하는 공간 메인페이지에서 nav바에서 유저입력부분-->
{% extends 'layout.html' %}
{% block content %}
<div class="contents">
    <div class="container">
        <div class="row" style="height: 1000px;">
            <div class="uploadfile_info">
               <h2>&#9889;자신의 파일(.pdf .docx .xls)의 단어 빈도수를 분석하여 순위를 알려드립니다!&#9889;</h2>
                <p>
                보안이 걸려있는 문서는 분석할 수 없습니다.<br>
                여러개의 파일을 zip으로 묶어 한 번에 분석할 수 있습니다.<br>
                워다타를 통해 가장 많이 나오는 영단어를 확인해보세요!<br>
                </p>
            </div>
            
            <div class="uploadfile_box" style="text-align: left;">
                <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.file }}
                    <div class="uploadfile">
                        <button id="custom-button"></button>
                        <input type="file" id="real-file" hidden="hidden" name=""> 
                    </div>
                    
                    <div style="display: inline-block; margin-bottom: 25px;">
                        <p>
                        제외할 단어<br>
                        <span style="font-size: 14px; color: #646464;">초등, 중등, 고등 영어단어들을<br>
                        제외하고 분석할 수 있습니다!!<br>
                        우측 네모박스를 눌러주세요 &#10138;<br>
                        (중등을 선택하면 초등도 포함됩니다.)</span>
                        </p>
                    </div>
                    
                    <div class="center">
                            {{ form.word_except }}
                        <select name="" id="sources" class="custom-select sources">
                            <option value="False">제외 안함</option>
                            <option value="1">초등학교 영어단어</option>
                            <option value="2">중학교 영어단어</option>
                            <option value="3">고등학교 영어단어</option>
                        </select>
                    </div>
                    
                    <p>
                    빈도수 최소값
                    <span style="font-size: 14px">(입력한 숫자의 미만 값의 빈도수 단어는 제외됩니다.)</span>
                    </p>
                    {{ form.frequency }}
                    <input type="text" name="" placeholder=" 5">
                    <p>
                    영어단어 개수
                    <span style="font-size: 14px">(1위부터 몇 위까지 알고싶은지 입력해주세요.)</span>
                    </p>
                    <input type="text" name="" placeholder=" 20">
                    {{ form.times }}
                    <button type="submit">분석 하러가기</button>
                    
                </form>
            </div>

            <p><a href="{% url 'main:home' %}">Return to home</a></p>
            <!-- uploadfile-->
            
        </div>
    </div>
</div>
<!--  contents -->
{% endblock %}